# Controls when the workflow will run
on:
  # Allows you to run this workflow manually ftarget the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.output }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { repo: 'ThePythonator/Super-Square-Bros',                output: 'Super-Square-Bros',  dir: ''} 
          - { repo: 'ThePythonator/Jumpy-Squirrel',                   output: 'Jumpy-Squirrel',     dir: ''}
          - { repo: 'ThePythonator/Ping',                             output: 'Ping',               dir: ''}
          
          - { repo: 'ahnlak-blit32/32blox',                           output: '32blox',             dir: ''} 
          - { repo: 'ahnlak-blit32/sokoblit',                         output: 'sokoblit',           dir: ''}
          
          - { repo: 'lummi01/32Blit-4_in_a_row',                      output: '4inrow',             dir: ''}
          - { repo: 'lummi01/32Blit-AlienAttack',                     output: 'alienattack',        dir: ''}
          - { repo: 'lummi01/32Blit-Asteroids',                       output: 'asteroids',          dir: ''}
          - { repo: 'lummi01/32Blit-Cannonhead',                      output: 'cannonhead',         dir: ''}
          - { repo: 'lummi01/32Blit-Invader',                         output: 'invader',            dir: ''}
          - { repo: 'lummi01/32Blit-Pitfall-Harry',                   output: 'harry',              dir: ''}
          - { repo: 'lummi01/32Blit-SnakeRace',                       output: 'snake2',             dir: ''}
          - { repo: 'lummi01/32Blit-Save-the-Castle',                 output: 'castle',             dir: ''}
          - { repo: 'lummi01/32Blit-Indy500',                         output: 'indy',               dir: ''}
          - { repo: 'lummi01/32Blit-MissileCommand',                  output: 'missile',            dir: ''}
          - { repo: 'lummi01/32Blit-Dodgeem',                         output: 'dodgeem',            dir: ''}
          - { repo: 'lummi01/32Blit-Tower',                           output: 'tower',              dir: ''}
          - { repo: 'lummi01/32Blit-game-of-life',                    output: 'gol',                dir: ''}
          - { repo: 'lummi01/32Blit-Dino',                            output: 'dino',               dir: ''}
          - { repo: 'lummi01/32Blit-Bounce',                          output: 'bounce',             dir: ''}
          - { repo: 'lummi01/32Blit-SimonSays',                       output: 'simon',              dir: ''}
          - { repo: 'lummi01/32Blit-Snake',                           output: 'Snake',              dir: ''}

          - { repo: 'shane-powell/blit-racers',                       output: 'blit-racers',        dir: ''}
        
          - { repo: 'Daft-Freak/fourblock-descent',                   output: 'fourblock-descent',  dir: ''}
          - { repo: 'Daft-Freak/super-blit-kart',                     output: 'blit-kart',          dir: ''}
  
          - { repo: '32blit/rocks-and-diamonds',                      output: 'rocks-and-diamonds', dir: ''}
          
          - { repo: 'ArtemHarkusha/32blit-minesweeper',               output: 'minesweeper',        dir: ''}
          - { repo: 'ArtemHarkusha/32blit-2048',                      output: '2048',               dir: ''}
          
          - { repo: 'ThatOtherOtherBob/Solitaire',                    output: 'Solitaire',          dir: ''}
          
          - { repo: 'Gadgetoid/32blit-dots',                          output: 'dots',               dir: ''}
          
          - { repo: 'Blackhawk-TA/TowerDefense',                      output: 'TowerDefense',       dir: ''}
          
          - { repo: 'deckerego/picosystem-demo',                      output: 'match3',             dir: ''}
          
          - { repo: 'andreban/32blit-a-maze',                         output: 'amaze',              dir: ''}
          
          - { repo: 'felipemanga/Armadillo32Blit',                    output: 'armadillo',          dir: ''}
          
          - { repo: 'joyrider3774/formula1_32blit',                   output: 'Formula1',          dir: ''}
          - { repo: 'joyrider3774/waternet_32blit',                   output: 'Waternet',          dir: ''}
          

        # these will contain bins for all the games in the repo as subdir building did not work so be it  
          - { repo: 'mikerr/32blit-games',                            output: 'carsprint',          dir: ''}
          - { repo: 'mikerr/32blit-games',                            output: 'dune2',              dir: ''}
        
          - { repo: 'mikerr/32blit-games',                            output: 'jetpac',             dir: ''}
          - { repo: 'mikerr/32blit-games',                            output: 'knightlore',         dir: ''}
          - { repo: 'mikerr/32blit-games',                            output: 'willy',              dir: ''}
          - { repo: 'mikerr/32blit-games',                            output: 'wakkawakka',         dir: ''}
                             
          - { repo: '32blit/32blit-examples',                         output: 'geometry',           dir: ''}   
          - { repo: '32blit/32blit-examples',                         output: 'raycaster',          dir: ''}
          - { repo: '32blit/32blit-examples',                         output: 'scrolly-tile',       dir: ''}  

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
               
      - name: get SDK
        uses: wei/wget@v1
        with:
          args: -O rg35xx_plus_aarch64.tgz https://github.com/joyrider3774/sdks/releases/download/v1.0/aarch64-buildroot-linux-gnu_sdk-buildroot.tar.gz

      - name: setup SDK
        run: |
          tar -xzvf ./rg35xx_plus_aarch64.tgz
          sudo mv ./aarch64-buildroot-linux-gnu_sdk-buildroot /opt/
          #force manual search
          sudo rm -rf /opt/aarch64-buildroot-linux-gnu_sdk-buildroot/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/SDL2_net
          sudo rm -rf /opt/aarch64-buildroot-linux-gnu_sdk-buildroot/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/SDL2_image
      
      - name: Checkout 32Blit sdk
        uses: actions/checkout@v2
        with:
          repository: joyrider3774/32blit-sdk
          path: 32blit-sdk
          ref: muos
                
      - name: setup 32blit extras
        run: |
          cd ${{runner.workspace}}
          python3 -m venv 32blit
          source ${{runner.workspace}}/32blit/bin/activate
          python3 -m pip install setuptools
          python3 -m pip install 32blit 
          
      - name: Checkout game sources sources
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          repository: ${{matrix.repo}}
          path: tmp
     
      - name: Create 32blit Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/tmp/${{matrix.dir}}/build
        
      - name: Configure CMake 32blit
        working-directory: ${{runner.workspace}}/tmp/${{matrix.dir}}/build
        run: |
          source ${{runner.workspace}}/32blit/bin/activate 
          cmake $GITHUB_WORKSPACE/tmp/${{matrix.dir}} -DCMAKE_BUILD_TYPE=Release -DCPACK_PACKAGE_FILE_NAME=${{ matrix.output}} -D32BLIT_DIR=$GITHUB_WORKSPACE/32blit-sdk -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/muos_aarch64_cmake/toolchainfile.cmake
      
      - name: Build 32blit game
        working-directory: ${{runner.workspace}}/tmp/${{matrix.dir}}/build
        shell: bash
        run: |
          source ${{runner.workspace}}/32blit/bin/activate
          cmake --build . --config Release
          
      - name: prepare opk directory
        run: |
          mkdir output
          mkdir output/.${{matrix.output}}
          mkdir output/.${{matrix.output}}/bin
          
           
      - name: Package for ${{matrix.output}} 32blit game
        working-directory: ${{runner.workspace}}/tmp/${{matrix.dir}}/build
        run: |
          source ${{runner.workspace}}/32blit/bin/activate
          cmake --build . --config Release --target package
          
      - name: Extract Package for ${{matrix.output}} 32blit game
        run: |
          cd output/.${{matrix.output}}
          tar -xzvf ${{runner.workspace}}/tmp/${{matrix.dir}}/build/${{ matrix.output }}.tar.gz
                      
      - name: create ${{matrix.output}}.sh general stuff
        run: |
          echo "#!/bin/sh" > "./output/${{matrix.output}}.sh"
          echo ". /opt/muos/script/var/func.sh" >> "./output/${{matrix.output}}.sh"
          echo "HOME=\"\$(GET_VAR \"device\" \"board/home\")\"" >> "./output/${{matrix.output}}.sh"
          echo "export HOME"  >> "./output/${{matrix.output}}.sh"
          
          echo "if [ \"\$(GET_VAR \"global\" \"boot/device_mode\")\" -eq 1 ]; then"  >> "./output/${{matrix.output}}.sh"
          echo "SDL_HQ_SCALER=2" >> "./output/${{matrix.output}}.sh"          
          echo "SDL_ROTATION=0" >> "./output/${{matrix.output}}.sh"          
          echo "SDL_BLITTER_DISABLED=1" >> "./output/${{matrix.output}}.sh" 
          echo "else" >> "./output/${{matrix.output}}.sh"
          echo "SDL_HQ_SCALER=\"\$(GET_VAR \"device\" \"sdl/scaler\")\"" >> "./output/${{matrix.output}}.sh"
          echo "SDL_ROTATION=\"\$(GET_VAR \"device\" \"sdl/rotation\")\"" >> "./output/${{matrix.output}}.sh"
          echo "SDL_BLITTER_DISABLED=\"\$(GET_VAR \"device\" \"sdl/blitter_disabled\")\"" >> "./output/${{matrix.output}}.sh"
          echo "fi" >> "./output/${{matrix.output}}.sh"
          echo "export SDL_HQ_SCALER SDL_ROTATION SDL_BLITTER_DISABLED" >> "./output/${{matrix.output}}.sh"

          echo "SET_VAR \"system\" \"foreground_process\" \"${{ matrix.output }}\"" >> "./output/${{matrix.output}}.sh"
         
          echo "SDL_GAMECONTROLLERCONFIG=\$(grep \"muOS-Keys\" \"/opt/muos/device/current/control/gamecontrollerdb_retro.txt\")" >> "./output/${{matrix.output}}.sh"
          echo "export SDL_GAMECONTROLLERCONFIG" >> "./output/${{matrix.output}}.sh"
          
          echo "GAMEFOLDER=\$(dirname \"\$0\")/.${{matrix.output}}" >> "./output/${{matrix.output}}.sh"
          echo "cd \"\$GAMEFOLDER/bin\"" >> "./output/${{matrix.output}}.sh"
          echo "./${{matrix.output}} --fullscreen" >> "./output/${{matrix.output}}.sh"
          
          chmod +x "./output/${{matrix.output}}.sh"
            
      - name: Store build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }} - 32blit - AARCH64 - Muos 
          path: output
          include-hidden-files: true
